version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
    depends_on:
      - client
      - api
    logging:
      driver: none
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/app
    environment:
      - DBNAME=capita
      - DBUSER=stevenesuh
      - DBHOST=host.docker.internal
      - DBPORT=5432
      - DBPASS=
      - PASSWORD_SALT=monkeypp
      - PLAID_ENV=development
      - PLAID_CLIENT_ID=5d0f62f4ea9b600016aca27f
      - PLAID_SECRET=a205d7ba390ddde25027d76157aaf5
      - PLAID_PUBLIC_KEY=7b7a1d74be67a52e518559eae6dbd5
      - PLAID_COUNTRY_CODES=US
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - REACT_APP_PLAID_ENV=development
      - REACT_APP_PLAID_PUBLIC_KEY=7b7a1d74be67a52e518559eae6dbd5
